/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Branding {
  'tagLine' : string,
  'heroBadge' : string,
  'logoFile' : [] | [string],
  'brandName' : string,
}
export interface GenRecordEntry {
  'metadata' : string,
  'createdAt' : bigint,
  'type' : GenType,
  'recordId' : bigint,
  'prompt' : string,
}
export type GenType = { 'video' : null } |
  { 'text' : null } |
  { 'sound' : null } |
  { 'image' : null };
export interface HomePageContent {
  'heroSubtitle' : string,
  'branding' : Branding,
  'heroTitle' : string,
  'premiumSection' : string,
  'freeSection' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type WebsiteState = { 'active' : null } |
  { 'retired' : { 'message' : [] | [string] } };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGenRecord' : ActorMethod<[GenType, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteGenRecord' : ActorMethod<[bigint], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGenHistory' : ActorMethod<[], Array<GenRecordEntry>>,
  'getHomepageContent' : ActorMethod<[], HomePageContent>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWebsiteStatus' : ActorMethod<[], WebsiteState>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'purgeData' : ActorMethod<[], undefined>,
  'reactivateWebsite' : ActorMethod<[], undefined>,
  'retireWebsite' : ActorMethod<[[] | [string]], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateGenRecord' : ActorMethod<[bigint, GenType, string, string], undefined>,
  'updateHomepageContent' : ActorMethod<[HomePageContent], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];