/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GenType = IDL.Variant({
  'video' : IDL.Null,
  'text' : IDL.Null,
  'sound' : IDL.Null,
  'image' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const GenRecordEntry = IDL.Record({
  'metadata' : IDL.Text,
  'createdAt' : IDL.Int,
  'type' : GenType,
  'recordId' : IDL.Nat,
  'prompt' : IDL.Text,
});
export const Branding = IDL.Record({
  'tagLine' : IDL.Text,
  'heroBadge' : IDL.Text,
  'logoFile' : IDL.Opt(IDL.Text),
  'brandName' : IDL.Text,
});
export const HomePageContent = IDL.Record({
  'heroSubtitle' : IDL.Text,
  'branding' : Branding,
  'heroTitle' : IDL.Text,
  'premiumSection' : IDL.Text,
  'freeSection' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGenRecord' : IDL.Func([GenType, IDL.Text, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteGenRecord' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGenHistory' : IDL.Func([], [IDL.Vec(GenRecordEntry)], ['query']),
  'getHomepageContent' : IDL.Func([], [HomePageContent], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateGenRecord' : IDL.Func([IDL.Nat, GenType, IDL.Text, IDL.Text], [], []),
  'updateHomepageContent' : IDL.Func([HomePageContent], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GenType = IDL.Variant({
    'video' : IDL.Null,
    'text' : IDL.Null,
    'sound' : IDL.Null,
    'image' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const GenRecordEntry = IDL.Record({
    'metadata' : IDL.Text,
    'createdAt' : IDL.Int,
    'type' : GenType,
    'recordId' : IDL.Nat,
    'prompt' : IDL.Text,
  });
  const Branding = IDL.Record({
    'tagLine' : IDL.Text,
    'heroBadge' : IDL.Text,
    'logoFile' : IDL.Opt(IDL.Text),
    'brandName' : IDL.Text,
  });
  const HomePageContent = IDL.Record({
    'heroSubtitle' : IDL.Text,
    'branding' : Branding,
    'heroTitle' : IDL.Text,
    'premiumSection' : IDL.Text,
    'freeSection' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGenRecord' : IDL.Func([GenType, IDL.Text, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteGenRecord' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGenHistory' : IDL.Func([], [IDL.Vec(GenRecordEntry)], ['query']),
    'getHomepageContent' : IDL.Func([], [HomePageContent], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateGenRecord' : IDL.Func(
        [IDL.Nat, GenType, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateHomepageContent' : IDL.Func([HomePageContent], [], []),
  });
};

export const init = ({ IDL }) => { return []; };