/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface HomePageContent {
    heroSubtitle: string;
    branding: Branding;
    heroTitle: string;
    premiumSection: string;
    freeSection: string;
}
export interface GenRecordEntry {
    metadata: string;
    createdAt: bigint;
    type: GenType;
    recordId: bigint;
    prompt: string;
}
export type WebsiteState = {
    __kind__: "active";
    active: null;
} | {
    __kind__: "retired";
    retired: {
        message?: string;
    };
};
export interface Branding {
    tagLine: string;
    heroBadge: string;
    logoFile?: string;
    brandName: string;
}
export interface UserProfile {
    name: string;
}
export enum GenType {
    video = "video",
    text = "text",
    sound = "sound",
    image = "image"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addGenRecord(type: GenType, prompt: string, metadata: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteGenRecord(recordId: bigint): Promise<boolean>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getGenHistory(): Promise<Array<GenRecordEntry>>;
    getHomepageContent(): Promise<HomePageContent>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWebsiteStatus(): Promise<WebsiteState>;
    isCallerAdmin(): Promise<boolean>;
    purgeData(): Promise<void>;
    reactivateWebsite(): Promise<void>;
    retireWebsite(message: string | null): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateGenRecord(recordId: bigint, newType: GenType, newPrompt: string, newMetadata: string): Promise<void>;
    updateHomepageContent(content: HomePageContent): Promise<void>;
}
import type { Branding as _Branding, GenRecordEntry as _GenRecordEntry, GenType as _GenType, HomePageContent as _HomePageContent, UserProfile as _UserProfile, UserRole as _UserRole, WebsiteState as _WebsiteState } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addGenRecord(arg0: GenType, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addGenRecord(to_candid_GenType_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGenRecord(to_candid_GenType_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteGenRecord(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGenRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGenRecord(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGenHistory(): Promise<Array<GenRecordEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGenHistory();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGenHistory();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHomepageContent(): Promise<HomePageContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getHomepageContent();
                return from_candid_HomePageContent_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHomepageContent();
            return from_candid_HomePageContent_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWebsiteStatus(): Promise<WebsiteState> {
        if (this.processError) {
            try {
                const result = await this.actor.getWebsiteStatus();
                return from_candid_WebsiteState_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWebsiteStatus();
            return from_candid_WebsiteState_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async purgeData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.purgeData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purgeData();
            return result;
        }
    }
    async reactivateWebsite(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reactivateWebsite();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reactivateWebsite();
            return result;
        }
    }
    async retireWebsite(arg0: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.retireWebsite(to_candid_opt_n21(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.retireWebsite(to_candid_opt_n21(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateGenRecord(arg0: bigint, arg1: GenType, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGenRecord(arg0, to_candid_GenType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGenRecord(arg0, to_candid_GenType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async updateHomepageContent(arg0: HomePageContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHomepageContent(to_candid_HomePageContent_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHomepageContent(to_candid_HomePageContent_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Branding_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Branding): Branding {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_GenRecordEntry_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GenRecordEntry): GenRecordEntry {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_GenType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GenType): GenType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_HomePageContent_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HomePageContent): HomePageContent {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_WebsiteState_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WebsiteState): WebsiteState {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    metadata: string;
    createdAt: bigint;
    type: _GenType;
    recordId: bigint;
    prompt: string;
}): {
    metadata: string;
    createdAt: bigint;
    type: GenType;
    recordId: bigint;
    prompt: string;
} {
    return {
        metadata: value.metadata,
        createdAt: value.createdAt,
        type: from_candid_GenType_n11(_uploadFile, _downloadFile, value.type),
        recordId: value.recordId,
        prompt: value.prompt
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    heroSubtitle: string;
    branding: _Branding;
    heroTitle: string;
    premiumSection: string;
    freeSection: string;
}): {
    heroSubtitle: string;
    branding: Branding;
    heroTitle: string;
    premiumSection: string;
    freeSection: string;
} {
    return {
        heroSubtitle: value.heroSubtitle,
        branding: from_candid_Branding_n15(_uploadFile, _downloadFile, value.branding),
        heroTitle: value.heroTitle,
        premiumSection: value.premiumSection,
        freeSection: value.freeSection
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tagLine: string;
    heroBadge: string;
    logoFile: [] | [string];
    brandName: string;
}): {
    tagLine: string;
    heroBadge: string;
    logoFile?: string;
    brandName: string;
} {
    return {
        tagLine: value.tagLine,
        heroBadge: value.heroBadge,
        logoFile: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.logoFile)),
        brandName: value.brandName
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    message: [] | [string];
}): {
    message?: string;
} {
    return {
        message: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.message))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: null;
} | {
    text: null;
} | {
    sound: null;
} | {
    image: null;
}): GenType {
    return "video" in value ? GenType.video : "text" in value ? GenType.text : "sound" in value ? GenType.sound : "image" in value ? GenType.image : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    retired: {
        message: [] | [string];
    };
}): {
    __kind__: "active";
    active: null;
} | {
    __kind__: "retired";
    retired: {
        message?: string;
    };
} {
    return "active" in value ? {
        __kind__: "active",
        active: value.active
    } : "retired" in value ? {
        __kind__: "retired",
        retired: from_candid_record_n20(_uploadFile, _downloadFile, value.retired)
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GenRecordEntry>): Array<GenRecordEntry> {
    return value.map((x)=>from_candid_GenRecordEntry_n9(_uploadFile, _downloadFile, x));
}
function to_candid_Branding_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Branding): _Branding {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_GenType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GenType): _GenType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_HomePageContent_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HomePageContent): _HomePageContent {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    heroSubtitle: string;
    branding: Branding;
    heroTitle: string;
    premiumSection: string;
    freeSection: string;
}): {
    heroSubtitle: string;
    branding: _Branding;
    heroTitle: string;
    premiumSection: string;
    freeSection: string;
} {
    return {
        heroSubtitle: value.heroSubtitle,
        branding: to_candid_Branding_n24(_uploadFile, _downloadFile, value.branding),
        heroTitle: value.heroTitle,
        premiumSection: value.premiumSection,
        freeSection: value.freeSection
    };
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tagLine: string;
    heroBadge: string;
    logoFile?: string;
    brandName: string;
}): {
    tagLine: string;
    heroBadge: string;
    logoFile: [] | [string];
    brandName: string;
} {
    return {
        tagLine: value.tagLine,
        heroBadge: value.heroBadge,
        logoFile: value.logoFile ? candid_some(value.logoFile) : candid_none(),
        brandName: value.brandName
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GenType): {
    video: null;
} | {
    text: null;
} | {
    sound: null;
} | {
    image: null;
} {
    return value == GenType.video ? {
        video: null
    } : value == GenType.text ? {
        text: null
    } : value == GenType.sound ? {
        sound: null
    } : value == GenType.image ? {
        image: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
